source: #Source stream for rules.
  url: https://api.gnip.com/accounts/{ACCOUNT_NAME}/publishers/twitter/streams/track/{STREAM_LABEL}/rules.json

target: #Target stream for rules.
  url: https://gnip-api.twitter.com/rules/powertrack/accounts/{ACCOUNT_NAME}/publishers/twitter/{STREAM_LABEL}.json

options:
  write_mode: file           #Options: file, api
  rules_folder: ./rules       #If generating rule JSON files, where to write them. Also source for JSON payloads to POST.
  rules_json_to_post: ''      #JSON file (path and name) to load into Target system via Rules API.
  verbose: false              #When true, the app writes more to system out.
  
logging:
  name: rule_migrator.log
  log_path: ./log
  warn_level: info
  size: 1 #MB
  keep: 1
